OpenJPEG: auxtrans_manager.h File Reference
auxtrans_manager.h File Reference
#include "sock_manager.h"
#include "opj_includes.h"
Data Structures
struct auxtrans_param
auxiliary transport setting parameters
Typedefs
typedef struct auxtrans_param auxtrans_param_t
auxiliary transport setting parameters
Functions
auxtrans_param_t init_aux_transport (int tcp_auxport, int udp_auxport)
Initialize auxiliary transport server of JPIP server.
void close_aux_transport (auxtrans_param_t auxtrans)
Close auxiliary transport server of JPIP server.
void send_responsedata_on_aux (OPJ_BOOL istcp, auxtrans_param_t auxtrans, const char cid[], void *data, OPJ_SIZE_T length, OPJ_SIZE_T maxlenPerFrame)
Send response data on aux transport.
Typedef Documentation
typedef struct auxtrans_param auxtrans_param_t
auxiliary transport setting parameters
Function Documentation
void close_aux_transport (auxtrans_param_t auxtrans)
Close auxiliary transport server of JPIP server.
Parameters
[in] auxtrans closing transport server
auxiliary response parameters
References close_socket(), auxtrans_param::tcplistensock, and auxtrans_param::udplistensock.
auxtrans_param_t init_aux_transport (int tcp_auxport, int udp_auxport)
Initialize auxiliary transport server of JPIP server.
Parameters
[in] tcp_auxport opening tcp auxiliary port (0 not to open, valid No. 49152-65535)
[in] udp_auxport opening udp auxiliary port (0 not to open, valid No. 49152-65535)
Returns
initialized transport parameters
References open_listeningsocket(), auxtrans_param::tcpauxport, auxtrans_param::tcplistensock, auxtrans_param::udpauxport, and auxtrans_param::udplistensock.
void send_responsedata_on_aux (OPJ_BOOL istcp, auxtrans_param_t auxtrans, const char cid[], void * data, OPJ_SIZE_T length, OPJ_SIZE_T maxlenPerFrame)
Send response data on aux transport.
Parameters
[in] istcp true if tcp, false if udp
[in] auxtrans available transport parameters
[in] cid channel ID
[in] data sending data
[in] length length of data
[in] maxlenPerFrame maximum data length to send per frame
References aux_streaming(), FCGI_stderr, gene_auxresponse(), and auxtrans_param::tcplistensock.