OpenJPEG: marker_manager.c File Reference
marker_manager.c File Reference
#include "marker_manager.h"
Macros
#define FCGI_stdout stdout
#define FCGI_stderr stderr
#define logstream stderr
Functions
marker_param_t set_marker (codestream_param_t cs, Byte2_t code, OPJ_OFF_T offset, Byte2_t length)
set marker parameters from inputs
Byte_t fetch_marker1byte (marker_param_t marker, OPJ_OFF_T offset)
fetch marker content 1-bytes of data in file stream
Byte2_t fetch_marker2bytebigendian (marker_param_t marker, OPJ_OFF_T offset)
fetch marker content 2-byte big endian Byte codes in file stream
Byte4_t fetch_marker4bytebigendian (marker_param_t marker, OPJ_OFF_T offset)
fetch marker content 4-byte big endian Byte codes in file stream
Macro Definition Documentation
#define FCGI_stderr stderr
#define FCGI_stdout stdout
#define logstream stderr
Function Documentation
Byte_t fetch_marker1byte (marker_param_t marker, OPJ_OFF_T offset)
fetch marker content 1-bytes of data in file stream
Parameters
[in] marker marker structure
[in] offset start Byte position in marker
Returns
fetched code
References marker_param::cs, fetch_codestream1byte(), and marker_param::offset.
Referenced by set_CODmkrdata(), and set_SIZmkrdata().
Byte2_t fetch_marker2bytebigendian (marker_param_t marker, OPJ_OFF_T offset)
fetch marker content 2-byte big endian Byte codes in file stream
Parameters
[in] marker marker structure
[in] offset start Byte position in marker
Returns
fetched code
References marker_param::cs, fetch_codestream2bytebigendian(), and marker_param::offset.
Referenced by set_CODmkrdata(), and set_SIZmkrdata().
Byte4_t fetch_marker4bytebigendian (marker_param_t marker, OPJ_OFF_T offset)
fetch marker content 4-byte big endian Byte codes in file stream
Parameters
[in] marker marker structure
[in] offset start Byte position in marker
Returns
fetched code
References marker_param::cs, fetch_codestream4bytebigendian(), and marker_param::offset.
Referenced by set_SIZmkrdata().
marker_param_t set_marker (codestream_param_t cs, Byte2_t code, OPJ_OFF_T offset, Byte2_t length)
set marker parameters from inputs
Parameters
[in] cs marker code
[in] code marker code
[in] offset offset in the codestream
[in] length marker segment length
Returns
structure of generated marker parameters
References marker_param::code, marker_param::cs, marker_param::length, and marker_param::offset.
Referenced by set_CODmkrdata(), and set_SIZmkrdata().