OpenJPEG: mhixbox_manager.h File Reference
mhixbox_manager.h File Reference
#include "byte_manager.h"
#include "box_manager.h"
Data Structures
struct markeridx_param
Marker index parameters.
struct mhixbox_param
header index table box parameters
Typedefs
typedef struct markeridx_param markeridx_param_t
Marker index parameters.
typedef struct mhixbox_param mhixbox_param_t
header index table box parameters
Functions
mhixbox_param_t * gene_mhixbox (box_param_t *box)
generate mhix box
markeridx_param_t * search_markeridx (Byte2_t code, mhixbox_param_t *mhix)
search a marker index by marker code from mhix box
void print_mhixbox (mhixbox_param_t *mhix)
print mhix box parameters
void print_markeridx (markeridx_param_t *markeridx)
print marker index parameters
void delete_mhixbox (mhixbox_param_t **mhix)
delete mhix box
Typedef Documentation
typedef struct markeridx_param markeridx_param_t
Marker index parameters.
typedef struct mhixbox_param mhixbox_param_t
header index table box parameters
I.3.2.4.3 Header Index Table box
Function Documentation
void delete_mhixbox (mhixbox_param_t ** mhix)
delete mhix box
Parameters
[in,out] mhix address of the mhix box pointer
References markeridx_param::next.
Referenced by delete_index(), and set_mainmhixdata().
mhixbox_param_t* gene_mhixbox (box_param_t * box)
generate mhix box
Parameters
[in] box pointer to the reference mhix box
Returns
generated mhixbox pointer
References markeridx_param::code, fetch_DBox2bytebigendian(), fetch_DBox8bytebigendian(), mhixbox_param::first, get_DBoxlen(), markeridx_param::length, markeridx_param::next, markeridx_param::num_remain, markeridx_param::offset, and mhixbox_param::tlen.
Referenced by set_mainmhixdata(), and set_thixdata().
void print_markeridx (markeridx_param_t * markeridx)
print marker index parameters
Parameters
[in] markeridx marker index pointer
References markeridx_param::code, markeridx_param::length, logstream, markeridx_param::num_remain, and markeridx_param::offset.
void print_mhixbox (mhixbox_param_t * mhix)
print mhix box parameters
Parameters
[in] mhix mhix box pointer
References markeridx_param::code, mhixbox_param::first, markeridx_param::length, logstream, markeridx_param::next, markeridx_param::num_remain, markeridx_param::offset, and mhixbox_param::tlen.
Referenced by print_index().
markeridx_param_t* search_markeridx (Byte2_t code, mhixbox_param_t * mhix)
search a marker index by marker code from mhix box
Parameters
[in] code marker code
[in] mhix mhix box pointer
Returns
found marker index pointer
References markeridx_param::code, FCGI_stderr, mhixbox_param::first, and markeridx_param::next.
Referenced by set_mainmhixdata().